CREATE TABLE battery (
    id INT AUTO_INCREMENT PRIMARY KEY,
    create_time DATETIME NULL,
    upload_time DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    bms_capacity TINYINT NULL,
    bms_total_power FLOAT NULL,
    bms_total_voltage FLOAT NULL,
    bms_monitor_voltage FLOAT NULL,
    bms_total_current FLOAT NULL,
    bms_generator_a_current FLOAT NULL,
    bms_generator_b_current FLOAT NULL,
    bms_sun_power_current FLOAT NULL,
    bms_battery_temperature FLOAT NULL,
    bms_battery_status TINYINT NULL,
    bms_relay_status VARCHAR(8) NULL,
    bms_flag VARCHAR(8) NULL,
    yeli_left_rpm SMALLINT UNSIGNED NULL,
    yeli_left_current FLOAT NULL,
    yeli_right_rpm SMALLINT UNSIGNED NULL,
    yeli_right_current FLOAT NULL,
    gps_latitude FLOAT NULL, 
    gps_longitude FLOAT NULL, 
    gps_angle FLOAT NULL,
    gps_speed FLOAT NULL
);